app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user, UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from flask import make_response
from flask import render_template_string
from flask import make_response, render_template, request
from . import mysql, login_manager
from datetime import datetime
import pandas as pd
from flask import send_file
import io
from xhtml2pdf import pisa
import MySQLdb.cursors
import pdfkit


config = pdfkit.configuration(
    wkhtmltopdf=r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe")




main = Blueprint("main", __name__)

class User(UserMixin):
    def __init__(self, id, username, password_hash, role):
        self.id = id
        self.username = username
        self.password_hash = password_hash
        self.role = role

@login_manager.user_loader
def load_user(user_id):
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM users WHERE id = %s", (user_id,))
    user = cur.fetchone()
    if user:
        return User(*user)
    return None

@main.route("/")
def index():
    return redirect(url_for("main.login"))

@main.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        cur = mysql.connection.cursor()
        cur.execute("SELECT * FROM users WHERE username = %s", (username,))
        user = cur.fetchone()
        if user and check_password_hash(user[2], password):
            user_obj = User(*user)
            login_user(user_obj)
            return redirect(url_for("main.dashboard"))
        else:
            flash("Invalid credentials", "danger")
            return redirect(url_for("main.login"))

    return render_template("login.html")


@main.route("/users")
@login_required
def list_users():
    if current_user.role != 'admin':
        flash("Akses ditolak", "danger")
        return redirect(url_for("main.dashboard"))

    cur = mysql.connection.cursor()
    cur.execute("SELECT id, username, role FROM users")
    users = cur.fetchall()
    return render_template("users/list.html", users=users)

@main.route("/users/add", methods=["GET", "POST"])
@login_required
def add_user():
    if current_user.role != 'admin':
        flash("Akses ditolak", "danger")
        return redirect(url_for("main.dashboard"))

    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        role = request.form["role"]

        password_hash = generate_password_hash(password)
        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO users (username, password_hash, role) VALUES (%s, %s, %s)",
                    (username, password_hash, role))
        mysql.connection.commit()
        flash("User berhasil ditambahkan", "success")
        return redirect(url_for("main.list_users"))

    return render_template("users/add.html")


@main.route("/dashboard")
@login_required
def dashboard():
    print("Role:", current_user.role)  # debug print
    return render_template("dashboard.html", name=current_user.username)



# ------------------------
# CRUD Produk
# ------------------------

@main.route("/products")
@login_required
def list_products():
    cur = mysql.connection.cursor()
    cur.execute("""
        SELECT id, code, name, category, purchase_price, price, stock_in, stock_sold
        FROM products
    """)
    products = cur.fetchall()
    return render_template("products/list.html", products=products)


@main.route("/products/list")
@login_required
def export_product():
    cur = mysql.connection.cursor()

    cur.execute("""
        SELECT code, name, category, stock_in, stock_sold, stock_live
        FROM products
    """)
    stok = cur.fetchall()
    df_stok = pd.DataFrame(stok, columns=["code", "name", "category", "stock_in", "stock_sold", "stock_live"])

    # Buat Excel dengan dua sheet
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        df_stok.to_excel(writer, sheet_name="stok_produk", index=False)

    output.seek(0)
    return send_file(output, download_name="laporan_transaksi.xlsx", as_attachment=True)

@main.route("/products/add", methods=["GET", "POST"])
@login_required
def add_product():
    if request.method == "POST":
        code = request.form["code"]
        name = request.form["name"]
        category = request.form["category"]
        purchase_price = float(request.form["purchase_price"])
        price = float(request.form["price"])
        stock_in = int(request.form["stock_in"])
        stock_sold = int(request.form["stock_sold"])
        
        cur = mysql.connection.cursor()
        cur.execute("""
            INSERT INTO products (code, name, category, purchase_price, price, stock_in, stock_sold)
            VALUES (%s, %s, %s, %s, %s, %s, %s )
        """,(code, name, category, purchase_price, price, stock_in, 0))
        mysql.connection.commit()
        flash("Produk berhasil ditambahkan", "success")
        return redirect(url_for("main.list_products"))
    
    return render_template("products/add.html")


@main.route("/products/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit_product(id):
    cur = mysql.connection.cursor()

    if request.method == "POST":
        code            = request.form["code"].strip()
        name            = request.form["name"].strip()
        category        = request.form["category"].strip()
        purchase_price  = float(request.form["purchase_price"])
        price           = float(request.form["price"])
        stock_in        = int(request.form["stock_in"])
        stock_sold      = int(request.form["stock_sold"])
        stock_live      = stock_in - stock_sold

        # ► urutan tuple = urutan kolom di query
        cur.execute("""
            UPDATE products
            SET code=%s,
                name=%s,
                category=%s,
                purchase_price=%s,
                price=%s,
                stock_in=%s,
                stock_sold=%s,
                stock_live=%s
            WHERE id=%s
        """, (code, name, category,
              purchase_price,
              price, stock_in, stock_sold, stock_live, id))   # id di akhir
        mysql.connection.commit()

        flash("Produk berhasil diperbarui", "success")
        return redirect(url_for("main.list_products"))

    # GET – ambil data produk untuk form
    cur.execute("SELECT * FROM products WHERE id=%s", (id,))
    product = cur.fetchone()
    return render_template("products/edit.html", product=product)


@main.route("/products/delete/<int:id>")
@login_required
def delete_product(id):
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM products WHERE id=%s", (id,))
    mysql.connection.commit()
    flash("Produk berhasil dihapus", "danger")
    return redirect(url_for("main.list_products"))


# ------------------------
# TRANSAKSI PEMBELIAN
# ------------------------


@main.route("/purchases")
@login_required
def purchases():
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute("SELECT id, name FROM products")
    products = cur.fetchall()
    return render_template("purchases/add.html", products=products)

@main.route("/purchases/add", methods=["POST"])
@login_required
def add_purchase():
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    if request.method == "POST":
        product_name = request.form["product_name"].strip()
        quantity = int(request.form["quantity"])
        try:
            purchase_price = float(request.form["purchase_price"])
        except ValueError:
            flash("Harga pembelian tidak valid", "danger")
            return redirect(url_for("main.purchases"))

        # Cek apakah produk sudah ada
        cur.execute("SELECT id FROM products WHERE name = %s", (product_name,))
        product = cur.fetchone()

        if product:
            product_id = product["id"]
        else:
            # Jika produk belum ada, tambahkan
            cur.execute("INSERT INTO products (name, stock_in) VALUES (%s, 0)", (product_name,))
            product_id = cur.lastrowid

        # Tambah ke tabel purchases
        cur.execute("INSERT INTO purchases (product_id, quantity, purchase_price) VALUES (%s, %s, %s)", (product_id, quantity, purchase_price))
        
        # Update stok produk
        cur.execute("UPDATE products SET stock_in = stock_in + %s WHERE id = %s", (quantity, product_id))

        cur.execute("""
            UPDATE products
            SET
                code            = COALESCE(code, %s),
                category        = COALESCE(category, %s),
                purchase_price  = CASE WHEN purchase_price = 0 THEN %s ELSE purchase_price END,
                price           = CASE WHEN price = 0 THEN %s ELSE price END
            WHERE id = %s
        """,(
            request.form.get("code") or None,
            request.form.get("category") or None,
            purchase_price,
            request.form.get("sell_price") or 0,
            product_id
        ))

        mysql.connection.commit()
        flash("Pembelian berhasil disimpan dan stok diperbarui", "success")
        return redirect(url_for("main.purchases"))

@main.route("/purchases/list")
@login_required
def list_purchases():
    cur = mysql.connection.cursor()
    query = """
        SELECT 
            p.id, pr.name, p.quantity, p.purchase_price, 
            (p.quantity * p.purchase_price) AS total_price,
            p.created_at
        FROM purchases p
        JOIN products pr ON p.product_id = pr.id
        ORDER BY p.created_at DESC
    """
    cur.execute(query)
    purchases = cur.fetchall()
    print("purchases", purchases)
    return render_template("purchases/list.html", purchases=purchases)




# ------------------------
# TRANSAKSI PENJUALAN

app/templates/products/add.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-4">
  <h3>Tambah Produk</h3>
  <form method="post">
    <div class="mb-2">
      <label>Kode Produk</label>
      <input type="text" name="code" class="form-control" required>
    </div>
    <div class="mb-2">
      <label>Nama Produk</label>
      <input type="text" name="name" class="form-control" required>
    </div>
    <div class="mb-2">
      <label>Kategori</label>
      <input type="text" name="category" class="form-control">
    </div>
    <div class="mb-2">
      <label>Harga Beli</label>
      <input type="number" name="purchase_price" class="form-control" required>
    </div>
    <div class="mb-2">
      <label>Harga Jual</label>
      <input type="number" name="price" class="form-control" required>
    </div>
    <div class="mb-2">
      <label>Stock Masuk</label>
      <input type="number" name="stock_in" class="form-control" required>
    </div>
    <div class="md-2">
      <label>Stock Keluar</label>
      <input type="number" name="stock_sold" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-success">Simpan</button>
    <a href="{{ url_for('main.list_products') }}" class="btn btn-secondary">Batal</a>
  </form>
</div>
{% endblock %}

app/templates/products/edit.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-4">
  <h3>Edit Produk</h3>
  <form method="post">
    <div class="mb-2">
      <label>Kode Produk</label>
      <input type="text" name="code" class="form-control" value="{{ product[1] }}" required>
    </div>
    <div class="mb-2">
      <label>Nama Produk</label>
      <input type="text" name="name" class="form-control" value="{{ product[2] }}" required>
    </div>
    <div class="mb-2">
      <label>Kategori</label>
      <input type="text" name="category" class="form-control" value="{{ product[3] }}">
    </div>
    <div class="mb-2">
      <label>Harga Beli</label>
      <div class="input-group">
        <span class="input-group-text">Rp</span>
        <input type="number" name="purchase_price" class="form-control"
                value="{{ product[4]|int }}" min="0" step="1" required>
      </div>
    </div>
    <div class="mb-2">
      <label>Harga Jual</label>
      <div class="input-group">
        <span class="input-group-text">Rp</span>
        <input type="number" name="price" class="form-control"
                value="{{ product[5]|int }}" min="0" step="1" required>
      </div>
    </div>
    <div class="mb-2">
      <label>Stock Masuk</label>
      <input type="number" name="stock_in" class="form-control" value="{{ product[6] }}" required>
    </div>
    <div class="mb-2">
      <label>Stock Keluar</label>
      <input type="number" name="stock_sold" class="form-control" value="{{ product[7]}}" required>
    </div>
    <button type="submit" class="btn btn-success">Simpan Perubahan</button>
    <a href="{{ url_for('main.list_products') }}" class="btn btn-secondary">Batal</a>
  </form>
</div>
{% endblock %}

app/templates/products/list.html
{% extends "layout.html" %}
{% block content %}

<style>
  /* Tambahan untuk kebutuhan print */
@media print {
  .sidebar,
  .navbar,
  .btn,
  .no-print,
  a[href*="/logout"],
  a[href*="/sales"],
  .bi-download,
  .watermark {
    display: none !important;
  }}
</style>

<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h3>Daftar Produk</h3>
    <div>
      <a href="{{ url_for('main.export_product') }}" class="btn btn-success mb-3">Download Excel</a>
      <a href="{{ url_for('main.add_product') }}" class="btn btn-primary mb-3">Tambah Produk</a>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <table class="table table-bordered table-hover table-striped">
    <thead class="table-dark text-center">
      <tr>
        <th>No</th>
        <th>Kode</th>
        <th>Nama</th>
        <th>Jenis</th>
        <th>Harga Beli</th>
        <th>Harga Jual</th>
        <th>Profit / Item</th>
        <th>Stock Masuk</th>
        <th>Terjual</th>
        <th>Stock Live</th>
        <th>Value</th>
        <th>Total Profit</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      {% for p in products %}
      <tr class="text-center">
        <td>{{ loop.index }}</td>
        <td>{{ p[1] }}</td> <!-- code -->
        <td>{{ p[2] }}</td> <!-- name -->
        <td>{{ p[3] }}</td> <!-- category -->
        <td>Rp{{ "{:,.0f}".format(p[4]) }}</td> <!-- purchase_price -->
        <td>Rp{{ "{:,.0f}".format(p[5]) }}</td> <!-- sell_price -->
        <td>Rp{{ "{:,.0f}".format(p[5] - p[4]) }}</td> <!-- profit/item -->
        <td>{{ p[6] }}</td> <!-- stock_in -->
        <td>{{ p[7] }}</td> <!-- sold -->
        <td>{{ p[6] - p[7] }}</td> <!-- stock live -->
        <td>Rp{{ "{:,.0f}".format((p[6] - p[7]) * p[5]) }}</td> <!-- value -->
        <td>Rp{{ "{:,.0f}".format(p[7] * (p[5] - p[4])) }}</td> <!-- total profit -->
        <td>
          <div class="d-flex justify-content-center gap-2">
            <a  href="{{ url_for('main.edit_product', id=p[0]) }}"
                class="btn btn-sm btn-warning"
                title="Edit">
                <i class="bi bi-pencil-square"></i>
            </a>
            <a  href="{{ url_for('main.delete_product', id=p[0]) }}"
                class="btn btn-sm btn-danger ms-1"
                title="Hapus"
                onclick="return confirm('Yakin ingin menghapus produk ini?')">
                <i class="bi bi-trash"></i>  
            </a>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}